POST http://localhost:3000/auth/refresh-tokens
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjExLCJlbWFpbCI6Im0uZG9lQGVtYWlsLmNvbSIsImlhdCI6MTczMjUzODk3MiwiZXhwIjoxNzMyNTQyNTcyLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.015JdkT8pbRUtveFD0nD-wAFs4cJ_xI5P6sU9o6lmyA

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjExLCJpYXQiOjE3MzI1Mzg5NzIsImV4cCI6MTczMjYyNTM3MiwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.BzCTJuIqizuH9vZJjjHRwvcFeT63D1n-cq8zRZNKTy8"
}